### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by Welchkimi** [cheungdaven/metricfactorization#1]
Hi, recently, I've read your paper "Metric Factorization: Recommendation beyond Matrix Factorization", so could you provide the source code for me?

**Comment by ThiagoSousa** [comment]
I just read the paper and I must say that I'm also very interested, I'd like to test it in other scenarios and with other evaluation metrics. Could you provide the source code? Thank you!

**Comment by cheungdaven** [comment]
@Welchkimi Hi, the code is available now

**Comment by cheungdaven** [comment]
@ThiagoSousa Hi, the code is available now
