### ISSUE TITLE
The problem of the MetricFRating.py

### ISSUE THREAD

**Issue by zijinchen** [cheungdaven/metricfactorization#6]
[80] test_set = list(test_data.keys())
[81] for (u, i) in test_set:

作者您好，您这里 test_data 为DataFrame格式，keys()只能取得列标，从而不存在（u，i)，按照道理这里应该是个字典才符合要求，您的代码可以跑通，而且效果不错，所以就比较疑惑，不知有什么问题，如果能指点一二，非常感谢！

**Comment by cheungdaven** [comment]
test_data是sparse matrix应该。
